# Generated by Django 4.2 on 2023-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
